### ISSUE TITLE
Why should accuracy be used as loss？

### ISSUE THREAD

**Issue by evelynly61** [fundamentalvision/Uni-Perceiver#2]
It seems 'argmax function' in accuracy calculation cannot backpropagate the gradient,so why accuracy be used as loss?

**Comment by Lechatelia** [comment]
As you said, the `accuracy ` doesn't backpropagate any gradient; removing it from the training configuration will not affect the training results.
 In fact, we just calculate training accuracy like a loss calculation and then write its result into the log files and tensorboard as a monitoring metric.
