### ISSUE TITLE
Instructions of preprocessing GLUE benchmark data.

### ISSUE THREAD

**Issue by hongliang-wei** [fundamentalvision/Uni-Perceiver#4]
Thank you for such a wonderful work. Can you describe how to preprocess the GLUE dataset? I failed to find out how to preprocess GLUE from [ GLUE-baselines](https://github.com/nyu-mll/GLUE-baselines).

**Comment by Lechatelia** [comment]
Sorry for missing such important information.
I have updated this in _readme_. Specifically, I preprocessed GLUE by using the tools from [fairseq repo](https://github.com/facebookresearch/fairseq/blob/main/examples/roberta/README.glue.md).
And our dataset can read the pre-processed data directly.

Please let me know if you have any other problems.

**Comment by hongliang-wei** [comment]
Thank you!
