### ISSUE TITLE
Where can I download "open_source_dataset/imagenet_class_name.pkl" in prompt tuning?

### ISSUE THREAD

**Issue by yix-chen** [fundamentalvision/Uni-Perceiver#6]

**Comment by Lechatelia** [comment]
Hey, the `cfg.DATALOADER.CLASS_NAME_FILE` has been departed in our new code and the file would not be used in the dataset.
Sorry for our oversight that we did not remove that in some configurations.
You could delete this line
`CLASS_NAME_FILE: 'open_source_dataset/imagenet_class_name.pkl' `
or set the path of new shared targets
`'open_source_dataset/imagenet_class_name_CLIP_with_endoftext.pkl'`
