### ISSUE TITLE
Meaning and role of SHARED_TARGETS?

### ISSUE THREAD

**Issue by hongliang-wei** [fundamentalvision/Uni-Perceiver#7]
Thank you for such a wonderful work. Would you please explain the meaning and role of SHARED_TARGETS?

**Comment by Lechatelia** [comment]
As Uni-Perceiver has no task-specific head (e.g., 1000-classes classification head for Imagenet1k), it will calculate the deep representation for targets (e.g., class names). For open-set classification tasks like Imagenet, the category names are fixed, thus, all GPUs can share the targets. Moreover, the shared targets can be partitioned to different GPUs to save memory costs, which is useful especially for tasks with too many class names, such as ImageNet21k.
