### ISSUE TITLE
关于结果准确率

### ISSUE THREAD

**Issue by FanqingM** [fundamentalvision/Uni-Perceiver#8]
您好，我使用您提供的base model（768）那个pth，在ImageNet1k的valid上直接做推理，但是准确率只有68-70%左右，和您论文中相差比较远，想问问是为什么

**Comment by Lechatelia** [comment]
非常不好意思，我把微信号邮件发给您，我们微信排查一下问题

**Comment by FanqingM** [comment]
已解决，感谢
